services:
  nostr-bot-en:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-bot-en
    command: ["./nostr_bot", "NOSTR_PRIVATE_KEY_EN"]
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    restart: 'no'
    environment:
      - BOT_PROCESSING_LANGUAGE=en
      # These can be set in .env or use defaults here if not in .env
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CONSOLE_LOG=${CONSOLE_LOG:-false}
      - DEBUG=${DEBUG:-false}
      # NOSTR_PRIVATE_KEY_EN must be in .env

  nostr-bot-ru:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-bot-ru
    command: ["./nostr_bot", "NOSTR_PRIVATE_KEY_RU"]
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    restart: 'no'
    environment:
      - BOT_PROCESSING_LANGUAGE=ru
      # These can be set in .env or use defaults here if not in .env
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CONSOLE_LOG=${CONSOLE_LOG:-false}
      - DEBUG=${DEBUG:-false}
      # NOSTR_PRIVATE_KEY_RU must be in .env

  nostr-bot-en-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-bot-en-test
    command: ["./nostr_bot", "NOSTR_PRIVATE_KEY_ENT"]
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    restart: 'no'
    environment:
      - BOT_PROCESSING_LANGUAGE=en
      - LOG_LEVEL=${LOG_LEVEL:-debug} # Default to debug for tests
      - CONSOLE_LOG=${CONSOLE_LOG:-true} # Default to console for tests
      - DEBUG=${DEBUG:-true}
      # NOSTR_PRIVATE_KEY_ENT must be in .env

  nostr-bot-ru-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-bot-ru-test
    command: ["./nostr_bot", "NOSTR_PRIVATE_KEY_RUT"]
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs # Consider separate logs/metrics for tests if needed
      - ./metrics:/app/metrics # e.g., ./logs-test:/app/logs
    restart: 'no'
    environment:
      - BOT_PROCESSING_LANGUAGE=ru
      - LOG_LEVEL=${LOG_LEVEL:-debug} # Default to debug for tests
      - CONSOLE_LOG=${CONSOLE_LOG:-true} # Default to console for tests
      - DEBUG=${DEBUG:-true}
      # NOSTR_PRIVATE_KEY_RUT must be in .env 